/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi;

import com.gradle.CustomLib;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(CustomLib.identifier);
        System.out.println(new App().getGreeting());
    }
}
